---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: phabricator
  name: phabricator-data-pv
  labels:
    name: phabricator-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 0.0.0.0
    path: /exports/k8s/phabricator/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: phabricator
  name: phabricator-mariadb-pv
  labels:
    name: phabricator-mariadb-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 0.0.0.0
    path: /exports/k8s/phabricator/mariadb
